version: "3"
services:
  app:
    container_name: projet
    restart: always
    build: .
    env_file:
      - api.env
    ports:
      - "8000:8000"
  mongo:
    container_name: mongo
    image: mongo
