version: "3"
services:
  api:
    build: .
    image: api
    command: npm start
    restart: always
    env_file:
      - api.env
  mongo:
    image: mongo
    restart: always
    volumes:
      - db:/data/db
  mongo_users:
    image: mongo
    restart: always
    volumes:
      - db_users:/data/db

volumes:
  db:
  db_users:
