name: API CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          touch ./api/api.env
          echo PORT=8000 >> ./api/api.env
          echo MONGO_URL=mongodb://mongo:27017/cartons >> ./api/api.env
          echo MONGO_URL_USERS=mongodb://mongo_users:27017/users >> ./api/api.env
          echo REDIS_URL=redis://redis_store >> ./api/api.env
          echo SESSION_SECRET=mon_secret_pas_secret >> ./api/api.env
          echo ALPHA=false >> ./api/api.env
          cat ./api/api.env
      - name: Run the API tests suite in a Docker environment
        run: docker-compose -f ./api/docker-compose.yml -f ./api/test/docker-compose.yml up --build --abort-on-container-exit
